# Generated by Django 4.0 on 2021-12-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_alter_participant_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='age',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
